<a href="https://colab.research.google.com/github/mehak-kalia/COE_Sabudh_Assignments-to-dos/blob/main/Numpy_Coursework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#question 1

import numpy as np
a = np.array( [ [1, 2], [2, 1] ] )
n=3
a=np.pad(a, pad_width=n)
a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 2, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
#question 2

import numpy as np


arr = np.arange(3 * 4 * 4).reshape(3, 4, 4)

print("Original 3d array:\n",
	arr)


diag_arr = np.diagonal(arr,
					axis1 = 1,
					axis2 = 2)

print("2d diagonal array:\n",
	diag_arr)


Original 3d array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
2d diagonal array:
 [[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]


In [ ]:
#question 3

import numpy as np
vec = np.arange(10)
 
vec_norm = np.linalg.norm(vec)
 
print("Vector norm:")
print(vec_norm)

Vector norm:
16.881943016134134


In [ ]:
#question 4

import numpy as np
np.random.randint(-10.0, 10.0, (6,6))


array([[ -4,  -4,  -2,   7,   1,  -6],
       [  9,   1,  -5,  -5,   8, -10],
       [  1,   6,  -2,  -5,   1,   0],
       [  4,   2,   4,  -1,   6,   0],
       [  8,   2,  -6,   5,   8,   3],
       [  0, -10,   0,   9,  -2, -10]])

In [ ]:
#question 5

import numpy as np
rand_num = np.random.normal(0,1,25)
print("25 random numbers from a standard normal distribution:")
print(rand_num)

25 random numbers from a standard normal distribution:
[-0.42624241 -0.88514646  0.15451978  0.62929592 -0.2466929   0.06714759
 -0.75010448  0.83231736  0.07738976  0.75745111  0.17251006 -1.6503807
 -0.39509948 -0.95568672 -0.72649175  1.02263176 -1.40809763  2.36903525
 -0.80377418 -1.67164816  0.28810105  1.14336393 -0.07090105  0.99047069
 -1.31391301]


In [ ]:
#question 6

a=np.arange(4).reshape(2,2)
b=np.arange(2)

print(" Horizontal joining")
print(np.column_stack((a,b)))

print(" Vertical joining")
print(np.row_stack((a,b)))


 Horizontal joining
[[0 1 0]
 [2 3 1]]
 Vertical joining
[[0 1]
 [2 3]
 [0 1]]


In [ ]:
#question 7

array=np.arange(24).reshape(3,4,2)
print(np.reshape(array, (24,1)))
print(np.reshape(array, (1,24)))
print(np.reshape(array, (2,12)))
print(np.reshape(array, (12,2)))
print(np.reshape(array, (8,3)))
print(np.reshape(array, (3,8)))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
